### ISSUE TITLE
Traceback on Windows 10 - Plugin fails to load

### ISSUE THREAD

**Issue by Bow-Lof-Petunias** [NoFoolLikeOne/EDMC-Screenshot#37]
Difficult to catalog the entire galaxy without this great plugin.
Started erroring as of 2020-11-18.
I've deleted the contents of  C:\Users\%user%\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-master and copied a fresh download of EDMC-Screenshot-3.4.0 into the directory but issue of plugin failing to load persists.
Reboot PC, "just in case"

2020-11-18 05:05:10.875 - ERROR - plug.Plugin.get_app:145: Failed for Plugin "Screenshot"
Traceback (most recent call last):
  File "plug.pyc", line 135, in get_app
  File "C:\Users\rich\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-master\load.py", line 219, in plugin_app
    this.status = HyperlinkLabel(this.container, anchor=tk.W, text=this.status_text)
AttributeError: module 'plugin_EDMC-Screenshot-master' has no attribute 'status_text'

2020-11-18 05:07:56.779 - ERROR - plug.notify_journal_entry:318: Plugin "Screenshot" failed
Traceback (most recent call last):
  File "plug.pyc", line 315, in notify_journal_entry
  File "C:\Users\rich\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-master\load.py", line 443, in journal_entry
    this.status['text'] = 'error'
AttributeError: module 'plugin_EDMC-Screenshot-master' has no attribute 'status'

**Comment by EekaDroid** [comment]
Hello, im also having issues loading the plugin. It started yesterday afternoon (17/11/2020). 

I'm having the following error:

> File "C:\Users\Name\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\load.py", line 76, in checkVersion
    for line in versions.content.decode("ascii").split("\r\n"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 320: ordinal not in range(128)

At line 67 the 'load.py' script tries to access a docs.google.com spreadsheet that is not accessible. Maybe this is what causing havoc in the script.

The line 76 is related to a function that tries to update the plugin, using the mentioned spreadsheet url. I managed to get the plugin running by bypassing this function.

Here is what i did (this is a temporary workaround, while our dev get things fixed):
1 - open the load.py script ("C:\Users\%UserName%\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\load.py") with notepad++;
2 - add '	this.status_text = "Ready"' (without apostrophe, you can copy-paste it) into line 73;
3 - comment the following lines, adding a '#' (without apostrophe) into lines 74 to 84 and line 221;
4 - done;

**Comment by Bow-Lof-Petunias** [comment]
> Here is what i did (this is a temporary workaround, while our dev get things fixed):
> 1 - open the load.py script ("C:\Users%UserName%\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\load.py") with notepad++;
> 2 - add ' this.status_text = "Ready"' (without apostrophe, starting with the space, you can copy-paste it) into line 73;
> 3 - comment the following lines, adding a '#' (without apostrophe) in the beginning of lines 74 to 84 and line 221;
> 4 - the plugin should load now, but with no auto update function;

This workaround resolved the issue for me.  Thanks for the prompt response.  Looking forward to an 'official' update soon™

**Comment by NoFoolLikeOne** [comment]
Thanks, I'll look into it

**Comment by NoFoolLikeOne** [comment]
Should be sorted now. Google changed the way permissions worked with published sheets. Before long programatic access to google sheets will all be metered

**Comment by Ambient-Impact** [comment]
@EekaDroid Thanks for the workaround!

@NoFoolLikeOne Thanks for the quick fix, and generally for this awesome plug-in.
