### ISSUE TITLE
Needs update for EDMC v5

### ISSUE THREAD

**Issue by Taomyn** [NoFoolLikeOne/EDMC-Screenshot#40]
Plugin no longer loads with EDMC v5 which is now in release candidate testing.

```
2021-05-09 21:09:30.441 - INFO - 9220:2352:2352 plug.Plugin.__init__:49: loading plugin "EDMC-Screenshot-3_4_0" from "C:\Users\Fernando\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\load.py"
2021-05-09 21:09:30.446 - ERROR - 9220:2352:2352 plug.Plugin.__init__:64: : Failed for Plugin "EDMC-Screenshot-3.4.0"
Traceback (most recent call last):
  File "plug.pyc", line 51, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Fernando\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\load.py", line 16, in <module>
    from PIL3 import Image
  File "C:\Users\Fernando\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\PIL3\Image.py", line 90, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL3' (C:\Users\Fernando\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\PIL3\__init__.py)
2021-05-09 21:09:30.448 - ERROR - 9220:2352:2352 plug.load_plugins:161: Failure loading found Plugin "EDMC-Screenshot-3.4.0"
Traceback (most recent call last):
  File "plug.pyc", line 159, in load_plugins
  File "plug.pyc", line 51, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Fernando\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\load.py", line 16, in <module>
    from PIL3 import Image
  File "C:\Users\Fernando\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\PIL3\Image.py", line 90, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL3' (C:\Users\Fernando\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-3.4.0\PIL3\__init__.py)
```

**Comment by NoFoolLikeOne** [comment]
Fixed

**Comment by Taomyn** [comment]
Thank-you
