### ISSUE TITLE
(Non-issue) Access is denied to ED default screenshot path

### ISSUE THREAD

**Issue by zsdonny** [NoFoolLikeOne/EDMC-Screenshot#44]
> [Screenshot] display: 1
> [Screenshot] Hide Display
> [Screenshot] C:\Users\Donny\Saved Games\Frontier Developments\Elite Dangerous\status.json
> [Screenshot] 0
> [Screenshot] ehZ:\Screenshot\EDMC-Screenshot
> [Screenshot] Output Directory: Z:\Screenshot\EDMC-Screenshot/Trapezium Sector YU-X c1-2
> [Screenshot] Output Mask: HighRes_Trapezium Sector YU-X c1-2(1 a)_[0123456789][0123456789][0123456789][0123456789][0123456789].png
> [Screenshot] getFileMask: Z:\Screenshot\EDMC-Screenshot/Trapezium Sector YU-X c1-2/HighRes_Trapezium Sector YU-X c1-2(1 a)_00002.png
> [Screenshot] delete in 60.0 seconds C:\Users\Donny\Pictures\Frontier Developments\Elite Dangerous\HighResScreenShot_2021-06-27_11-18-53.bmp
> [Screenshot] deleting C:\Users\Donny\Pictures\Frontier Developments\Elite Dangerous\HighResScreenShot_2021-06-27_11-18-53.bmp
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "tkinter\__init__.pyc", line 1892, in __call__
>   File "tkinter\__init__.pyc", line 814, in callit
>   File "C:\Users\Donny\AppData\Local\EDMarketConnector\plugins\Screenshot\load.py", line 517, in delete_first
>     os.remove(original)
> PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Donny\\Pictures\\Frontier Developments\\Elite Dangerous\\HighResScreenShot_2021-06-27_11-18-53.bmp'

This is not an application issue but I am just wondering since the plugin has a feature to delete the source image after moving it to the processed folder location, does anyone have a solution to EDMC not having Windows permission to deleting from the default ED screenshot folder inside the '%userprofile%\Pictures?' beside like running EDMC in administrator mode?

I really appreciate the converting into .png routine that helps with high-res screenshot so I really want to use this haha

**Comment by zsdonny** [comment]
> [Screenshot] C:\Users\Donny\Saved Games\Frontier Developments\Elite Dangerous\status.json
> [Screenshot] 0
> [Screenshot] ehZ:\Screenshot\EDMC-Screenshot
> 2021-06-27 19:34:21.126 - ERROR - 20544:2272:2272 plug.notify_journal_entry:271: Plugin "Screenshot" failed
> Traceback (most recent call last):
>   File "plug.pyc", line 268, in notify_journal_entry
>   File "C:\Users\Donny\AppData\Local\EDMarketConnector\plugins\Screenshot\load.py", line 449, in journal_entry
>     converted = getFilename(entry['Filename'][13:], system, body, cmdr)
>   File "C:\Users\Donny\AppData\Local\EDMarketConnector\plugins\Screenshot\load.py", line 320, in getFilename
>     dir = getOutputDir(system)
>   File "C:\Users\Donny\AppData\Local\EDMarketConnector\plugins\Screenshot\load.py", line 275, in getOutputDir
>     make_sure_path_exists(this.png_loc.get() + '/' + system)
>   File "C:\Users\Donny\AppData\Local\EDMarketConnector\plugins\Screenshot\load.py", line 356, in make_sure_path_exists
>     os.makedirs(path)
>   File "os.pyc", line 215, in makedirs
>   File "os.pyc", line 215, in makedirs
>   File "os.pyc", line 215, in makedirs
>   File "os.pyc", line 225, in makedirs
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Z:\\'

Seems like running it in administrator mode wouldn't work too? Since I want my destination folder to be a network drive and it seems if it is run in administrator mode it will not recognize network path...
