### ISSUE TITLE
Processing screenshot statut and nothing more

### ISSUE THREAD

**Issue by Pauliakov** [NoFoolLikeOne/EDMC-Screenshot#48]
Hello
I installed the plugin and added the link to the screenshots but when I press F10 my screen is made and appears in my folder but the software stays on "Processing screenshot" and nothing happens after.

Have you ever had this problem ?
In the logs I have 

`2021-08-13 22:34:15.960 - ERROR - 11816:7340:7340 plug.notify_journal_entry:271: Plugin "Screenshot" failed Traceback (most recent call last):
  File "plug.pyc", line 268, in notify_journal_entry
  File "C:\Users\xxx\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-master\load.py", line 454, in journal_entry
    this.im.save(converted, "PNG")
  File "C:\Users\xxx\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-master\PIL39\Image.py", line 2169, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\xxx\\Desktop\\EliteDangerous\\Screenshots/Malayamatha_(3).png'`

**Comment by kokrull** [comment]
same here. also to note. if you have it set to the group in folders. it creates the folder with the star system name in the root of c: rather than in the elite dangerous folder

**Comment by Pauliakov** [comment]
Hello,

Not working for me.
it creates the folder but without screenshot in it.

**Comment by Leonardo150** [comment]
For me, it worked using as screenshot directory in this path C:\Users\XXXX\Pictures\Frontier Developments\Elite Dangerous.
The plugin created this directories in Pictures directory.

**Comment by jennbeckmann** [comment]
I am also having this issue.  I'm using EDMC 5.5.0 and playing on Odyssey. When I take a screenshot, it says "processing" and creates the system subdirectory folder. ... and that's it. I've tried running it without "group files" checked, and then it just hangs on "processing", but still nothing else happens. It detects a screenshot has been taken, it appropriately names the new subdirectory... but then nothing else seems to occur. I've tried searching elsewhere in files (to confirm the screenshots aren't being saved elsewhere), I've tried changing the directories in the settings, but no difference. No cropping window/thumbnail pops up either. It just seems to hang for a minute or two, and then end without doing anything other than creating a subdirectory.

**Comment by Leonardo150** [comment]
> I am also having this issue. I'm using EDMC 5.5.0 and playing on Odyssey. When I take a screenshot, it says "processing" and creates the system subdirectory folder. ... and that's it. I've tried running it without "group files" checked, and then it just hangs on "processing", but still nothing else happens. It detects a screenshot has been taken, it appropriately names the new subdirectory... but then nothing else seems to occur. I've tried searching elsewhere in files (to confirm the screenshots aren't being saved elsewhere), I've tried changing the directories in the settings, but no difference. No cropping window/thumbnail pops up either. It just seems to hang for a minute or two, and then end without doing anything other than creating a subdirectory.

worked for me using as screenshot directory in this path C:\Users\XXXX\Pictures\Frontier Developments\Elite Dangerous, but i chose another directory as conversion directory, the directory name have no quotation marks

**Comment by jennbeckmann** [comment]
> 

I saw your earlier comment that said this, I also tried it. It did not work for me.

**Comment by jennbeckmann** [comment]
> > I am also having this issue. I'm using EDMC 5.5.0 and playing on Odyssey. When I take a screenshot, it says "processing" and creates the system subdirectory folder. ... and that's it. I've tried running it without "group files" checked, and then it just hangs on "processing", but still nothing else happens. It detects a screenshot has been taken, it appropriately names the new subdirectory... but then nothing else seems to occur. I've tried searching elsewhere in files (to confirm the screenshots aren't being saved elsewhere), I've tried changing the directories in the settings, but no difference. No cropping window/thumbnail pops up either. It just seems to hang for a minute or two, and then end without doing anything other than creating a subdirectory.
> 
> worked for me using as screenshot directory in this path C:\Users\XXXX\Pictures\Frontier Developments\Elite Dangerous, but i chose another directory as conversion directory, the directory name have no quotation marks

I saw your earlier comment that said this, I also tried it. It did not work for me.

**Comment by Leonardo150** [comment]
> > > I am also having this issue. I'm using EDMC 5.5.0 and playing on Odyssey. When I take a screenshot, it says "processing" and creates the system subdirectory folder. ... and that's it. I've tried running it without "group files" checked, and then it just hangs on "processing", but still nothing else happens. It detects a screenshot has been taken, it appropriately names the new subdirectory... but then nothing else seems to occur. I've tried searching elsewhere in files (to confirm the screenshots aren't being saved elsewhere), I've tried changing the directories in the settings, but no difference. No cropping window/thumbnail pops up either. It just seems to hang for a minute or two, and then end without doing anything other than creating a subdirectory.
> > 
> > 
> > worked for me using as screenshot directory in this path C:\Users\XXXX\Pictures\Frontier Developments\Elite Dangerous, but i chose another directory as conversion directory, the directory name have no quotation marks
> 
> I saw your earlier comment that said this, I also tried it. It did not work for me.

See the log file, maybe it will help to solve the problem
