### ISSUE TITLE
Fails to load module on Linux Version of EDMC

### ISSUE THREAD

**Issue by cyberlink1** [NoFoolLikeOne/EDMC-Screenshot#54]
Im running in Linux and it fails to load the plugin when installed. Digging into it a little it looks like you may be using an OS Specific lib to do WinDLL calls instead of the cross platform libs. Though Im no expert on this.

**Comment by ThornedRose** [comment]
Also running Linux (Arch) and it fails to load for me. Other plugins work no problem.

**Comment by midigark** [comment]
> Im running in Linux and it fails to load the plugin when installed. Digging into it a little it looks like you may be using an OS Specific lib to do WinDLL calls instead of the cross platform libs. Though Im no expert on this.

Running from Linux Mint 21.3 using python3.10

Hey, I ran it in a terminal using $ python load.py
And get:
$ python load.py
Traceback (most recent call last):
  File "/home/me/.local/share/EDMarketConnector/plugins/EDMC-Screenshot/load.py", line 2, in <module>
    import key
  File "/home/me/.local/share/EDMarketConnector/plugins/EDMC-Screenshot/key.py", line 5, in <module>
    **user32 = ctypes.WinDLL('user32', use_last_error=True)**
**AttributeError: module 'ctypes' has no attribute 'WinDLL'**

==========
I'm going to guess that this version is _not_ "Linux friendly".

While not specifically stating that this would ruin under Linux, this stated that it would run under Python 3.7+.
[(https://github.com/EDCD/EDMarketConnector/wiki/Plugins)]

Maybe we all need to start using some visual indicators for what systems these will run on - as-is.
You know,  the penguin, winflag, etc...

![ostypes](https://github.com/NoFoolLikeOne/EDMC-Screenshot/assets/89489190/4db6baaa-b945-47b7-859c-1992ced9059c)

Mark
